[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:obscura]
command=/usr/local/bin/obscura serve --port 9222
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:searxng]
command=python3 -m granian searx.webapp:app --host 0.0.0.0 --port 8080 --interface wsgi
environment=SEARXNG_SETTINGS_PATH="/etc/searxng/settings.yml",SEARXNG_SECRET="piargus-search-2026"
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
